"""listing current price columns

Revision ID: e252f6926190
Revises: d9db8beb8af2
Create Date: 2026-10-01 22:58:13.477110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e252f6926190'
down_revision: Union[str, None] = 'd9db8beb8af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('listing', sa.Column('current_original_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('listing', sa.Column('current_discount_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_listing_current_discount_pct'), 'listing', ['current_discount_pct'], unique=False)
    op.create_index(op.f('ix_listing_current_price'), 'listing', ['current_price'], unique=False)
    # ### end Alembic commands ###

    # Backfill from each listing's latest snapshot.
    for column, source in [
        ("current_price", "price"),
        ("current_original_price", "original_price"),
        ("current_discount_pct", "discount_pct"),
    ]:
        op.execute(
            f"UPDATE listing SET {column} = (SELECT ps.{source} FROM price_snapshot ps "
            f"WHERE ps.listing_id = listing.id ORDER BY ps.scraped_at DESC, ps.id DESC LIMIT 1)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_current_price'), table_name='listing')
    op.drop_index(op.f('ix_listing_current_discount_pct'), table_name='listing')
    op.drop_column('listing', 'current_discount_pct')
    op.drop_column('listing', 'current_original_price')
    op.drop_column('listing', 'current_price')
    # ### end Alembic commands ###
